services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nest-crud-user-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest_crud_user
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nest_crud_user']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: nest-crud-user-migration
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_NAME: nest_crud_user
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run migration:run
    restart: 'no'

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: nest-crud-user-api
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_NAME: nest_crud_user

      MINIO_PUBLIC_ENDPOINT: localhost
      MINIO_PUBLIC_PORT: 9000
      MINIO_PUBLIC_USE_SSL: false
      MINIO_REGION: us-east-1

      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      MINIO_BUCKET: legal-documents
      MINIO_USE_SSL: false

      JWT_SECRET: K8vN2qX7mLp4Rz9JcT5wHy1BaUf6DsEe
      JWT_EXPIRES_IN_SECONDS: 3600

      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: admin
      ADMIN_NAME: Admin
      ADMIN_PHONE: '0123456789'
      ADMIN_DATE_OF_BIRTH: '2000-01-01'
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: nest-crud-user-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/data
    command: server /data --console-address ':9001'
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
